import os
import logging
from typing import Dict, Any, List

from src.ai_code_reviewer.domain.ports.vcs_service import VCSService
from src.ai_code_reviewer.domain.ports.llm_service import LLMService
from src.ai_code_reviewer.domain.ports.storage_service import StorageService
from src.ai_code_reviewer.domain.ports.cache_service import CacheService
from src.ai_code_reviewer.domain.services.review_parser import ReviewParser

logger = logging.getLogger(__name__)

class ReviewMRUseCase:
    """Use case for reviewing a merge request."""

    def __init__(
        self,
        vcs_service: VCSService,
        storage_service: StorageService,
        cache_service: CacheService,
        base_prompt: str,
        prompt_context_dir: str = "prompt-contexts",
    ):
        self.vcs_service = vcs_service
        self.storage_service = storage_service
        self.cache_service = cache_service
        self.base_prompt = base_prompt
        self.prompt_context_dir = prompt_context_dir

    def execute(self, project_path: str, mr_iid: int, llm_service: LLMService) -> Dict[str, Any]:
        """Executes the merge request review process, using cache if available."""
        logger.info(f"Executing review for MR !{mr_iid} in project '{project_path}' using {type(llm_service).__name__}.")

        """Executes the merge request review process, using cache if available."""
        logger.info(f"Executing review for MR !{mr_iid} in project '{project_path}' using {type(llm_service).__name__}.")

        # Check for forced review conditions
        force_env_var = os.getenv("AGENT_REVIEW_FORCE", "false").lower() == "true"
        mr_labels = self.vcs_service.get_merge_request_labels(project_path, mr_iid)
        requested_label = "agent-review-requested"
        has_requested_label = requested_label in mr_labels

        force_review = force_env_var or has_requested_label
        
        if force_review:
            logger.info("Forced review detected (env var or label). Bypassing 'already reviewed' check.")

        existing_comments = self.vcs_service.get_merge_request_comments(project_path, mr_iid)
        prefix_review = "<!-- agent-review-bot -->"
        
        if not force_review:
            for comment in existing_comments:
                if prefix_review in comment:
                    logger.info(f"MR !{mr_iid} in project '{project_path}' already reviewed by agent. Skipping.")
                    return {
                        "review": "",
                        "full_review": "",
                        "parsed_comments": [],
                        "review_file_path": "",
                        "skipped": True
                    }

        changes = self.vcs_service.get_merge_request_changes(project_path, mr_iid)

        rules = self._load_prompt_context(self.prompt_context_dir)
        prompt = self.base_prompt.format(rules=rules, changes=changes)

        # Check cache first
        # The cache key includes the LLM service name to avoid conflicts between models
        cache_key = f"{type(llm_service).__name__}_{prompt}"
        cached_review = self.cache_service.get(cache_key)
        if cached_review and os.getenv("USE_CACHE", "false").lower() in ("true", "1") and not force_review:
             # Only use cache if not forced
            review = cached_review
        else:
            # If not in cache, call the selected LLM and save to cache
            review = llm_service.analyze_code_changes(prompt)
            self.cache_service.set(cache_key, review)

        # Formato unificado para salvar localmente (mantém comportamento original)
        suffix_review = os.getenv("AGENT_REVIEW_SIGNATURE", "Generated by AI with ❤️")
        full_review_for_storage = f"{prefix_review}\n\n{review}\n\n{suffix_review}"

        # Salva o review COMPLETO e UNIFICADO no arquivo local
        review_file_path = self.storage_service.save_review(mr_iid, full_review_for_storage)

        # Parse review em comentários individuais (para preview e publicação)
        parsed_comments = ReviewParser.parse(review)
        
        # Remove label 'agent-review-requested' if it was present
        if has_requested_label:
            logger.info(f"Removing '{requested_label}' label after review execution.")
            self.vcs_service.remove_merge_request_label(project_path, mr_iid, requested_label)

        return {
            "review": review,                    # Review cru da LLM (sem prefixo/sufixo)
            "full_review": full_review_for_storage,  # Review completo para display
            "parsed_comments": parsed_comments,  # Lista de comentários parseados
            "review_file_path": review_file_path
        }

    def publish_review(self, project_path: str, merge_request_iid: int, review: str):
        """
        Publica o review como múltiplos comentários separados no MR do GitLab.

        O review é parseado usando o separador '---' e cada seção é postada
        como um comentário individual no Merge Request.
        Inclui retry automático com exponential backoff para rate limiting.

        Args:
            project_path: Caminho do projeto no GitLab
            merge_request_iid: IID do Merge Request
            review: Texto cru do review (sem prefixo/sufixo)
        """
        prefix_review = "<!-- agent-review-bot -->"
        suffix_review = os.getenv("AGENT_REVIEW_SIGNATURE", "Generated by AI with ❤️")

        # Parse review em comentários individuais
        parsed_comments = ReviewParser.parse(review)

        if not parsed_comments:
            logger.warning("No comments to publish - review was empty or couldn't be parsed")
            return

        # Prepara os comentários para envio ao GitLab
        comments_to_post: List[str] = []

        for i, comment in enumerate(parsed_comments):
            formatted_comment =  f"{prefix_review}\n\n{comment.content}\n\n{suffix_review}"
            comments_to_post.append(formatted_comment)

        logger.info(f"Publishing {len(comments_to_post)} comments with retry support")

        # O GitLabService agora lida com retry e throttling internamente
        self.vcs_service.post_comments_on_merge_request(
            project_path,
            merge_request_iid,
            comments_to_post
        )

    def _load_prompt_context(self, context_dir: str) -> str:
        logger.info(f"Loading prompt context from '{context_dir}' directory.")
        if not os.path.isdir(context_dir):
            logger.warning(f"Context directory not found: {context_dir}")
            return ""

        context_parts = []
        for filename in sorted(os.listdir(context_dir)):
            if filename.endswith(".md"):
                filepath = os.path.join(context_dir, filename)
                logger.debug(f"Loading context from file: {filepath}")
                with open(filepath, "r") as f:
                    context_parts.append(f.read())

        if not context_parts:
            logger.info("No context files found to load.")
            return ""

        logger.info(f"Loaded {len(context_parts)} context files.")
        return "\n\n".join(context_parts) + "\n\n---\n\n"
