import pytest
from unittest.mock import MagicMock

from src.code_review_agent.application.use_cases.review_mr import ReviewMRUseCase

# Fixtures to provide mocked services for the use case
@pytest.fixture
def mock_vcs_service():
    return MagicMock()

@pytest.fixture
def mock_llm_service():
    return MagicMock()

@pytest.fixture
def mock_storage_service():
    return MagicMock()

@pytest.fixture
def mock_cache_service():
    return MagicMock()

@pytest.fixture
def review_mr_use_case(mock_vcs_service, mock_llm_service, mock_storage_service, mock_cache_service):
    """Provides a ReviewMRUseCase instance with mocked dependencies."""
    return ReviewMRUseCase(
        vcs_service=mock_vcs_service,
        storage_service=mock_storage_service,
        cache_service=mock_cache_service,
        base_prompt="Base prompt: {rules} {changes}",
    )


def test_execute_cache_miss(review_mr_use_case, mock_vcs_service, mock_llm_service, mock_storage_service, mock_cache_service):
    """Test the successful execution when the review is not in the cache."""
    # Arrange
    project_id = "test/project"
    mr_iid = 1
    changes_data = {"changes": [{"diff": "..."}]}
    llm_review = "This is a great change!"
    saved_path = "reviews/2023-10-27/1/review.md"

    mock_vcs_service.get_merge_request_changes.return_value = changes_data
    mock_cache_service.get.return_value = None  # Cache miss
    mock_llm_service.analyze_code_changes.return_value = llm_review
    mock_storage_service.save_review.return_value = saved_path

    # Act
    result = review_mr_use_case.execute(project_id, mr_iid, mock_llm_service)

    # Assert
    mock_vcs_service.get_merge_request_changes.assert_called_once_with(project_id, mr_iid)

    expected_prompt = f"Base prompt: {review_mr_use_case._load_prompt_context('prompt_contexts')} {changes_data}"
    mock_cache_service.get.assert_called_once_with(expected_prompt)
    mock_llm_service.analyze_code_changes.assert_called_once_with(expected_prompt)
    mock_cache_service.set.assert_called_once_with(expected_prompt, llm_review)

    # Verifica que save_review foi chamado com o review completo (com prefixo/sufixo)
    expected_full_review = f"<!-- agent-review-bot -->\n\n{llm_review}\n\nGenerated by AI with ❤️"
    mock_storage_service.save_review.assert_called_once_with(mr_iid, expected_full_review)

    # Verifica o retorno inclui todos os campos esperados
    assert "review" in result
    assert "full_review" in result
    assert "parsed_comments" in result
    assert "review_file_path" in result
    assert result["review"] == llm_review
    assert result["review_file_path"] == saved_path
    assert result["full_review"] == expected_full_review


def test_execute_cache_hit(review_mr_use_case, mock_vcs_service, mock_llm_service, mock_storage_service, mock_cache_service):
    """Test the successful execution when the review is found in the cache."""
    # Arrange
    project_id = "test/project"
    mr_iid = 1
    changes_data = {"changes": [{"diff": "..."}]}
    cached_review = "This is a cached review."
    saved_path = "reviews/2023-10-27/1/review.md"

    mock_vcs_service.get_merge_request_changes.return_value = changes_data
    mock_cache_service.get.return_value = cached_review # Cache hit
    mock_storage_service.save_review.return_value = saved_path

    # Act
    result = review_mr_use_case.execute(project_id, mr_iid, mock_llm_service)

    # Assert
    expected_prompt = f"Base prompt: {review_mr_use_case._load_prompt_context('prompt_contexts')} {changes_data}"
    mock_cache_service.get.assert_called_once_with(expected_prompt)
    mock_llm_service.analyze_code_changes.assert_not_called() # Should not be called
    mock_cache_service.set.assert_not_called() # Should not be called

    # Verifica que save_review foi chamado com o review completo (com prefixo/sufixo)
    expected_full_review = f"<!-- agent-review-bot -->\n\n{cached_review}\n\nGenerated by AI with ❤️"
    mock_storage_service.save_review.assert_called_once_with(mr_iid, expected_full_review)

    # Verifica o retorno inclui todos os campos esperados
    assert "review" in result
    assert "full_review" in result
    assert "parsed_comments" in result
    assert "review_file_path" in result
    assert result["review"] == cached_review
    assert result["review_file_path"] == saved_path
    assert result["full_review"] == expected_full_review


def test_publish_review_single_comment(review_mr_use_case, mock_vcs_service):
    """Testa publicação de review com um único comentário."""
    # Arrange
    project_path = "test/project"
    mr_iid = 123
    review_text = "Este é um comentário único"

    # Act
    review_mr_use_case.publish_review(project_path, mr_iid, review_text)

    # Assert
    mock_vcs_service.post_comments_on_merge_request.assert_called_once()
    call_args = mock_vcs_service.post_comments_on_merge_request.call_args

    assert call_args[0][0] == project_path
    assert call_args[0][1] == mr_iid
    assert len(call_args[0][2]) == 1

    # Verifica que o comentário tem prefixo e sufixo
    comment = call_args[0][2][0]
    assert "<!-- agent-review-bot -->" in comment
    assert "Generated by AI with ❤️" in comment
    assert review_text in comment


def test_publish_review_multiple_comments(review_mr_use_case, mock_vcs_service):
    """Testa publicação de review com múltiplos comentários."""
    # Arrange
    project_path = "test/project"
    mr_iid = 123
    review_text = """Primeiro comentário
---
Segundo comentário
---
Terceiro comentário"""

    # Act
    review_mr_use_case.publish_review(project_path, mr_iid, review_text)

    # Assert
    mock_vcs_service.post_comments_on_merge_request.assert_called_once()
    call_args = mock_vcs_service.post_comments_on_merge_request.call_args

    assert call_args[0][0] == project_path
    assert call_args[0][1] == mr_iid
    comments = call_args[0][2]
    assert len(comments) == 3

    # Verifica que TODOS os comentários têm prefixo e sufixo
    prefix = "<!-- agent-review-bot -->"
    suffix = "Generated by AI with ❤️"

    for i, comment in enumerate(comments):
        assert prefix in comment, f"Comentário {i+1} deve ter prefixo"
        assert suffix in comment, f"Comentário {i+1} deve ter sufixo"
        # Verifica que o conteúdo do comentário está presente
        if i == 0:
            assert "Primeiro comentário" in comment
        elif i == 1:
            assert "Segundo comentário" in comment
        else:
            assert "Terceiro comentário" in comment


def test_publish_review_empty_review(review_mr_use_case, mock_vcs_service):
    """Testa que publicação de review vazio não faz nada."""
    # Arrange
    project_path = "test/project"
    mr_iid = 123
    review_text = ""

    # Act
    review_mr_use_case.publish_review(project_path, mr_iid, review_text)

    # Assert
    mock_vcs_service.post_comments_on_merge_request.assert_not_called()


def test_publish_review_only_separators(review_mr_use_case, mock_vcs_service):
    """Testa que publicação de review com apenas separadores não faz nada."""
    # Arrange
    project_path = "test/project"
    mr_iid = 123
    review_text = "---\n---\n---"

    # Act
    review_mr_use_case.publish_review(project_path, mr_iid, review_text)

    # Assert
    mock_vcs_service.post_comments_on_merge_request.assert_not_called()


def test_publish_review_all_comments_have_prefix_and_suffix(review_mr_use_case, mock_vcs_service):
    """Testa que TODOS os comentários têm prefixo e sufixo, não apenas o primeiro e último."""
    # Arrange
    project_path = "test/project"
    mr_iid = 123
    review_text = """Comentário 1
---
Comentário 2
---
Comentário 3
---
Comentário 4"""

    prefix = "<!-- agent-review-bot -->"
    suffix = "Generated by AI with ❤️"

    # Act
    review_mr_use_case.publish_review(project_path, mr_iid, review_text)

    # Assert
    call_args = mock_vcs_service.post_comments_on_merge_request.call_args
    comments = call_args[0][2]

    # Verifica que TODOS os 4 comentários têm prefixo e sufixo
    assert len(comments) == 4

    for i, comment in enumerate(comments, 1):
        assert prefix in comment, f"Comentário {i} deve ter prefixo"
        assert suffix in comment, f"Comentário {i} deve ter sufixo"
        # Verifica que o prefixo está no início e o sufixo no final
        assert comment.startswith(prefix), f"Comentário {i} deve começar com prefixo"
        assert comment.endswith(suffix), f"Comentário {i} deve terminar com sufixo"
